language: node_js
node_js:
  - "10"

sudo: false

install:
  - npm install

env:
  - SCRIPT=test
  - SCRIPT=lint-check

script:
  - npm run $SCRIPT

after_success:
#  - npm run shim:coverage && npm run shim:coveralls
